import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Problem from './models/Problem.model';
import User from './models/User.model';
dotenv.config();

const PYTHON_MINIMAL = `def solve():\n    # Write your solution here\n    pass\n\nif __name__ == "__main__":\n    solve()`;
const CPP_MINIMAL = `#include <iostream>\n#include <vector>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    // Write your solution here\n    return 0;\n}`;
const JAVA_MINIMAL = `import java.util.*;\n\nclass Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // Write your solution here\n    }\n}`;
const JS_MINIMAL = `// Write your solution here\n// Use console.log() to print output`;

const TEMPLATES = { python: PYTHON_MINIMAL, cpp: CPP_MINIMAL, java: JAVA_MINIMAL, javascript: JS_MINIMAL };

const PROBLEMS = [
  // ... (Existing 23 problems)
  { title:'Hello World', slug:'hello-world', difficulty:'Easy' as const, tags:['Basics','I/O'], description:'## Hello World\n\nPrint "Hello, World!" to standard output.', constraints:'No input required\nOutput: Hello, World!', examples:[{input:'',output:'Hello, World!'}], testCases:[{input:'',expectedOutput:'Hello, World!',isHidden:false}], starterTemplates:TEMPLATES, hints:['Use print() in Python'], isPublished:true },
  { title:'Sum of Two Numbers', slug:'sum-of-two-numbers', difficulty:'Easy' as const, tags:['Math','I/O'], description:'## Sum of Two Numbers\n\nRead two integers, print their sum.', constraints:'-10^9 <= A,B <= 10^9', examples:[{input:'3\n5',output:'8'}], testCases:[{input:'3\n5',expectedOutput:'8',isHidden:false},{input:'1000000000\n-1000000000',expectedOutput:'0',isHidden:true}], starterTemplates:TEMPLATES, hints:['Use long long in C++'], isPublished:true },
  { title:'Fibonacci Sequence', slug:'fibonacci-sequence', difficulty:'Easy' as const, tags:['Math','DP'], description:'## Fibonacci\n\nGiven N, print first N Fibonacci numbers.', constraints:'1 <= N <= 40', examples:[{input:'5',output:'0\n1\n1\n2\n3'}], testCases:[{input:'5',expectedOutput:'0\n1\n1\n2\n3',isHidden:false},{input:'10',expectedOutput:'0\n1\n1\n2\n3\n5\n8\n13\n21\n34',isHidden:true}], starterTemplates:TEMPLATES, hints:['Use two variables'], isPublished:true },
  { title:'Count Word Frequencies', slug:'count-word-frequencies', difficulty:'Medium' as const, tags:['String','HashMap'], description:'## Count Word Frequencies\n\nGiven a sentence, print each word with its count sorted alphabetically.', constraints:'1<=words<=10^4', examples:[{input:'the cat sat on the mat the cat',output:'cat 2\nmat 1\non 1\nsat 1\nthe 3'}], testCases:[{input:'the cat sat on the mat the cat',expectedOutput:'cat 2\nmat 1\non 1\nsat 1\nthe 3',isHidden:false}], starterTemplates:TEMPLATES, hints:['Use Counter'], isPublished:true },
  { title:'Reverse a String', slug:'reverse-a-string', difficulty:'Easy' as const, tags:['String','Basics'], description:'## Reverse a String\n\nRead a string and print it reversed.', constraints:'1<=len<=10^5', examples:[{input:'hello',output:'olleh'}], testCases:[{input:'hello',expectedOutput:'olleh',isHidden:false},{input:'abcde',expectedOutput:'edcba',isHidden:true}], starterTemplates:TEMPLATES, hints:['Slicing works in Python'], isPublished:true },
  { title:'Palindrome Check', slug:'palindrome-check', difficulty:'Easy' as const, tags:['String'], description:'## Palindrome Check\n\nCheck if a string is a palindrome. Print YES or NO.', constraints:'1<=len<=10^5, lowercase only', examples:[{input:'racecar',output:'YES'},{input:'hello',output:'NO'}], testCases:[{input:'racecar',expectedOutput:'YES',isHidden:false},{input:'hello',expectedOutput:'NO',isHidden:false},{input:'abcba',expectedOutput:'YES',isHidden:true}], starterTemplates:TEMPLATES, hints:['Compare with reversed'], isPublished:true },
  { title:'Find Maximum Element', slug:'find-maximum-element', difficulty:'Easy' as const, tags:['Array'], description:'## Find Maximum\n\nGiven N integers, find the maximum.', constraints:'1<=N<=10^5, -10^9<=arr[i]<=10^9', examples:[{input:'5\n3 1 4 1 5',output:'5'}], testCases:[{input:'5\n3 1 4 1 5',expectedOutput:'5',isHidden:false},{input:'3\n-1 -2 -3',expectedOutput:'-1',isHidden:true}], starterTemplates:TEMPLATES, hints:['Use built-in max()'], isPublished:true },
  { title:'Binary Search', slug:'binary-search', difficulty:'Easy' as const, tags:['Array','Binary Search'], description:'## Binary Search\n\nGiven a sorted array of N integers and a target T, print the 0-indexed position or -1.', constraints:'1<=N<=10^5', examples:[{input:'5\n1 3 5 7 9\n5',output:'2'}], testCases:[{input:'5\n1 3 5 7 9\n5',expectedOutput:'2',isHidden:false},{input:'4\n2 4 6 8\n5',expectedOutput:'-1',isHidden:true}], starterTemplates:TEMPLATES, hints:['Halve the search space each step'], isPublished:true },
  { title:'Two Sum', slug:'two-sum', difficulty:'Medium' as const, tags:['Array','HashMap'], description:'## Two Sum\n\nGiven N integers and target T, find two indices (0-indexed) whose values sum to T.', constraints:'2<=N<=10^4', examples:[{input:'4\n2 7 11 15\n9',output:'0 1'}], testCases:[{input:'4\n2 7 11 15\n9',expectedOutput:'0 1',isHidden:false},{input:'3\n3 2 4\n6',expectedOutput:'1 2',isHidden:true}], starterTemplates:TEMPLATES, hints:['Store complement in a dict'], isPublished:true },
  { title:'Balanced Parentheses', slug:'balanced-parentheses', difficulty:'Medium' as const, tags:['Stack','String'], description:'## Balanced Parentheses\n\nCheck if a string of brackets is balanced. Print YES or NO.', constraints:'1<=len<=10^5', examples:[{input:'()[]{}'  ,output:'YES'}], testCases:[{input:'()[]{}',expectedOutput:'YES',isHidden:false},{input:'([)]',expectedOutput:'NO',isHidden:false},{input:'{[()]}',expectedOutput:'YES',isHidden:true}], starterTemplates:TEMPLATES, hints:['Use a stack'], isPublished:true },
  { title:'Bubble Sort', slug:'bubble-sort', difficulty:'Easy' as const, tags:['Array','Sorting'], description:'## Bubble Sort\n\nSort N integers using bubble sort.', constraints:'1<=N<=10^3', examples:[{input:'5\n5 3 1 4 2',output:'1 2 3 4 5'}], testCases:[{input:'5\n5 3 1 4 2',expectedOutput:'1 2 3 4 5',isHidden:false}], starterTemplates:TEMPLATES, hints:['Swap adjacent elements'], isPublished:true },
  { title:'Coin Change', slug:'coin-change', difficulty:'Medium' as const, tags:['DP','Greedy'], description:'## Coin Change\n\nFind minimum coins needed for an amount. Print -1 if impossible.', constraints:'0<=amount<=10^4', examples:[{input:'3\n1 5 6\n11',output:'2'}], testCases:[{input:'3\n1 5 6\n11',expectedOutput:'2',isHidden:false},{input:'2\n2 5\n3',expectedOutput:'-1',isHidden:true}], starterTemplates:TEMPLATES, hints:['DP bottom-up'], isPublished:true },
  { title:'Number of Islands', slug:'number-of-islands', difficulty:'Hard' as const, tags:['Graph','BFS','DFS'], description:'## Number of Islands\n\nCount distinct islands in an NxM grid of 1s and 0s.', constraints:'1<=N,M<=300', examples:[{input:'4 5\n11110\n11010\n11000\n00000',output:'1'}], testCases:[{input:'4 5\n11110\n11010\n11000\n00000',expectedOutput:'1',isHidden:false},{input:'4 5\n11000\n11000\n00100\n00011',expectedOutput:'3',isHidden:true}], starterTemplates:TEMPLATES, hints:['BFS/DFS from land'], isPublished:true },
  { title:'Trapping Rain Water', slug:'trapping-rain-water', difficulty:'Hard' as const, tags:['Array','Two Pointers'], description:'## Trapping Rain Water\n\nCompute total water trapped by heights array.', constraints:'1<=N<=10^5', examples:[{input:'12\n0 1 0 2 1 0 1 3 2 1 2 1',output:'6'}], testCases:[{input:'12\n0 1 0 2 1 0 1 3 2 1 2 1',expectedOutput:'6',isHidden:false}], starterTemplates:TEMPLATES, hints:['Two-pointer technique'], isPublished:true },
  { title:'Merge Sort', slug:'merge-sort', difficulty:'Medium' as const, tags:['Array','Sorting'], description:'## Merge Sort\n\nSort N integers using merge sort.', constraints:'1<=N<=10^5', examples:[{input:'6\n38 27 43 3 9 82',output:'3 9 27 38 43 82'}], testCases:[{input:'6\n38 27 43 3 9 82',expectedOutput:'3 9 27 38 43 82',isHidden:false}], starterTemplates:TEMPLATES, hints:['Divide and conquer'], isPublished:true },
  { title:'Longest Common Subsequence', slug:'longest-common-subsequence', difficulty:'Medium' as const, tags:['DP','String'], description:'## LCS\n\nFind length of LCS of two strings.', constraints:'1<=len<=1000', examples:[{input:'abcde\nace',output:'3'}], testCases:[{input:'abcde\nace',expectedOutput:'3',isHidden:false}], starterTemplates:TEMPLATES, hints:['Classic 2D DP'], isPublished:true },
  { title:'N-Queens Problem', slug:'n-queens', difficulty:'Hard' as const, tags:['Backtracking'], description:'## N-Queens\n\nCount ways to place N queens.', constraints:'1<=N<=12', examples:[{input:'4',output:'2'}], testCases:[{input:'4',expectedOutput:'2',isHidden:false},{input:'8',expectedOutput:'92',isHidden:true}], starterTemplates:TEMPLATES, hints:['Backtrack'], isPublished:true },
  { title:'Power of a Number', slug:'power-of-number', difficulty:'Easy' as const, tags:['Math'], description:'## Fast Power\n\nCompute (base^exp) % (10^9+7).', constraints:'0<=base,exp<=10^9', examples:[{input:'2\n10',output:'1024'}], testCases:[{input:'2\n10',expectedOutput:'1024',isHidden:false}], starterTemplates:TEMPLATES, hints:['Modular exponentiation'], isPublished:true },
  { title:'Matrix Spiral Traversal', slug:'matrix-spiral', difficulty:'Medium' as const, tags:['Array','Matrix'], description:'## Spiral Traversal\n\nPrint matrix in spiral order.', constraints:'1<=N,M<=100', examples:[{input:'3 3\n1 2 3\n4 5 6\n7 8 9',output:'1 2 3 6 9 8 7 4 5'}], testCases:[{input:'3 3\n1 2 3\n4 5 6\n7 8 9',expectedOutput:'1 2 3 6 9 8 7 4 5',isHidden:false}], starterTemplates:TEMPLATES, hints:['Track borders'], isPublished:true },
  { title:'Stack Simulation', slug:'stack-simulation', difficulty:'Medium' as const, tags:['Stack'], description:'## Stack Simulation\n\nSimulate stack operations.', constraints:'1<=Q<=10^4', examples:[{input:'5\nPUSH 1\nPUSH 2\nPEEK\nPOP\nPOP',output:'2\n2\n1'}], testCases:[{input:'5\nPUSH 1\nPUSH 2\nPEEK\nPOP\nPOP',expectedOutput:'2\n2\n1',isHidden:false}], starterTemplates:TEMPLATES, hints:['Use a list'], isPublished:true },
  { title:'Binary Tree Level Order', slug:'binary-tree-level-order', difficulty:'Medium' as const, tags:['Tree','BFS'], description:'## Level Order\n\nGiven tree as parent array, print level by level.', constraints:'1<=N<=10^3', examples:[{input:'7\n-1 1 1 2 2 3 3',output:'1\n2 3\n4 5 6 7'}], testCases:[{input:'7\n-1 1 1 2 2 3 3',expectedOutput:'1\n2 3\n4 5 6 7',isHidden:false}], starterTemplates:TEMPLATES, hints:['BFS'], isPublished:true },
  { title:'Dijkstra Algorithm', slug:'dijkstra-algorithm', difficulty:'Hard' as const, tags:['Graph','Greedy'], description:'## Dijkstra\n\nFind shortest paths from node 1.', constraints:'1<=N,E<=10^4', examples:[{input:'4 4\n1 2 1\n2 3 2\n1 3 4\n3 4 1',output:'0 1 3 4'}], testCases:[{input:'4 4\n1 2 1\n2 3 2\n1 3 4\n3 4 1',expectedOutput:'0 1 3 4',isHidden:false}], starterTemplates:TEMPLATES, hints:['Min-heap'], isPublished:true },

  // NEW ARRAY PROBLEMS (20+)
  { title:'Contains Duplicate', slug:'contains-duplicate', difficulty:'Easy' as const, tags:['Array','HashSet'], description:'## Contains Duplicate\n\nGiven N integers, print YES if any value appears at least twice, otherwise print NO.', constraints:'1<=N<=10^5', examples:[{input:'4\n1 2 3 1',output:'YES'}], testCases:[{input:'4\n1 2 3 1',expectedOutput:'YES',isHidden:false},{input:'4\n1 2 3 4',expectedOutput:'NO',isHidden:false},{input:'1\n1',expectedOutput:'NO',isHidden:true}], starterTemplates:TEMPLATES, hints:['Use a set'], isPublished:true },
  { title:'Valid Anagram', slug:'valid-anagram', difficulty:'Easy' as const, tags:['String','HashMap'], description:'## Valid Anagram\n\nCheck if two strings S and T are anagrams. Print YES or NO.', constraints:'1<=len<=5*10^4', examples:[{input:'anagram\nnagaram',output:'YES'}], testCases:[{input:'anagram\nnagaram',expectedOutput:'YES',isHidden:false},{input:'rat\ncar',expectedOutput:'NO',isHidden:false}], starterTemplates:TEMPLATES, hints:['Count frequencies'], isPublished:true },
  { title:'Best Time to Buy and Sell Stock', slug:'best-time-to-buy-sell-stock', difficulty:'Easy' as const, tags:['Array','DP'], description:'## Best Time to Buy and Sell Stock\n\nGiven N prices, find the maximum profit from one buy and one sell. Print 0 if no profit possible.', constraints:'1<=N<=10^5', examples:[{input:'6\n7 1 5 3 6 4',output:'5'}], testCases:[{input:'6\n7 1 5 3 6 4',expectedOutput:'5',isHidden:false},{input:'5\n7 6 4 3 1',expectedOutput:'0',isHidden:false}], starterTemplates:TEMPLATES, hints:['Track min price'], isPublished:true },
  { title:'Maximum Subarray (Kadane)', slug:'maximum-subarray', difficulty:'Medium' as const, tags:['Array','DP'], description:'## Maximum Subarray\n\nFind the sum of the contiguous subarray with the largest sum.', constraints:'1<=N<=10^5', examples:[{input:'9\n-2 1 -3 4 -1 2 1 -5 4',output:'6'}], testCases:[{input:'9\n-2 1 -3 4 -1 2 1 -5 4',expectedOutput:'6',isHidden:false},{input:'1\n1',expectedOutput:'1',isHidden:false},{input:'5\n5 4 -1 7 8',expectedOutput:'15',isHidden:true}], starterTemplates:TEMPLATES, hints:['Kadane Algorithm'], isPublished:true },
  { title:'Product of Array Except Self', slug:'product-of-array-except-self', difficulty:'Medium' as const, tags:['Array'], description:'## Product Except Self\n\nGiven N integers, print an array where result[i] is the product of all elements except nums[i].', constraints:'2<=N<=10^5', examples:[{input:'4\n1 2 3 4',output:'24 12 8 6'}], testCases:[{input:'4\n1 2 3 4',expectedOutput:'24 12 8 6',isHidden:false},{input:'5\n-1 1 0 -3 3',expectedOutput:'0 0 9 0 0',isHidden:true}], starterTemplates:TEMPLATES, hints:['Prefix and suffix products'], isPublished:true },
  { title:'Maximum Product Subarray', slug:'maximum-product-subarray', difficulty:'Medium' as const, tags:['Array','DP'], description:'## Max Product Subarray\n\nFind the largest product of a contiguous subarray.', constraints:'1<=N<=2*10^4', examples:[{input:'4\n2 3 -2 4',output:'6'}], testCases:[{input:'4\n2 3 -2 4',expectedOutput:'6',isHidden:false},{input:'3\n-2 0 -1',expectedOutput:'0',isHidden:false}], starterTemplates:TEMPLATES, hints:['Track min and max product'], isPublished:true },
  { title:'Find Minimum in Rotated Sorted Array', slug:'find-min-rotated-sorted', difficulty:'Medium' as const, tags:['Array','Binary Search'], description:'## Find Min in Rotated Sorted Array\n\nFind the minimum element in a sorted array that was rotated.', constraints:'1<=N<=5000', examples:[{input:'5\n3 4 5 1 2',output:'1'}], testCases:[{input:'5\n3 4 5 1 2',expectedOutput:'1',isHidden:false},{input:'7\n4 5 6 7 0 1 2',expectedOutput:'0',isHidden:false}], starterTemplates:TEMPLATES, hints:['Modified binary search'], isPublished:true },
  { title:'Search in Rotated Sorted Array', slug:'search-rotated-sorted', difficulty:'Medium' as const, tags:['Array','Binary Search'], description:'## Search in Rotated Sorted Array\n\nSearch for a target in a rotated sorted array. Print index or -1.', constraints:'1<=N<=5000', examples:[{input:'7\n4 5 6 7 0 1 2\n0',output:'4'}], testCases:[{input:'7\n4 5 6 7 0 1 2\n0',expectedOutput:'4',isHidden:false},{input:'7\n4 5 6 7 0 1 2\n3',expectedOutput:'-1',isHidden:false}], starterTemplates:TEMPLATES, hints:['Modified binary search'], isPublished:true },
  { title:'3Sum', slug:'3sum', difficulty:'Medium' as const, tags:['Array','Two Pointers'], description:'## 3Sum\n\nFind all unique triplets that sum to zero. Print each triplet on a new line, sorted.', constraints:'3<=N<=3000', examples:[{input:'6\n-1 0 1 2 -1 -4',output:'-1 -1 2\n-1 0 1'}], testCases:[{input:'6\n-1 0 1 2 -1 -4',expectedOutput:'-1 -1 2\n-1 0 1',isHidden:false}], starterTemplates:TEMPLATES, hints:['Sort and two-pointer'], isPublished:true },
  { title:'Container With Most Water', slug:'container-with-most-water', difficulty:'Medium' as const, tags:['Array','Two Pointers'], description:'## Most Water\n\nFind the max area of water a container can hold between two vertical lines.', constraints:'2<=N<=10^5', examples:[{input:'9\n1 8 6 2 5 4 8 3 7',output:'49'}], testCases:[{input:'9\n1 8 6 2 5 4 8 3 7',expectedOutput:'49',isHidden:false}], starterTemplates:TEMPLATES, hints:['Two-pointer technique'], isPublished:true },
  { title:'Move Zeroes', slug:'move-zeroes', difficulty:'Easy' as const, tags:['Array'], description:'## Move Zeroes\n\nMove all 0s to the end while maintaining the relative order of non-zero elements.', constraints:'1<=N<=10^4', examples:[{input:'5\n0 1 0 3 12',output:'1 3 12 0 0'}], testCases:[{input:'5\n0 1 0 3 12',expectedOutput:'1 3 12 0 0',isHidden:false}], starterTemplates:TEMPLATES, hints:['Two pointers'], isPublished:true },
  { title:'Majority Element', slug:'majority-element', difficulty:'Easy' as const, tags:['Array','Boyer-Moore'], description:'## Majority Element\n\nFind the element that appears more than N/2 times.', constraints:'1<=N<=5*10^4', examples:[{input:'3\n3 2 3',output:'3'}], testCases:[{input:'3\n3 2 3',expectedOutput:'3',isHidden:false},{input:'7\n2 2 1 1 1 2 2',expectedOutput:'2',isHidden:false}], starterTemplates:TEMPLATES, hints:['Boyer-Moore Voting'], isPublished:true },
  { title:'Merge Sorted Array', slug:'merge-sorted-array', difficulty:'Easy' as const, tags:['Array','Two Pointers'], description:'## Merge Sorted Arrays\n\nGiven two sorted arrays, merge them into one sorted array.', constraints:'1<=N,M<=1000', examples:[{input:'3 3\n1 2 3\n2 5 6',output:'1 2 2 3 5 6'}], testCases:[{input:'3 3\n1 2 3\n2 5 6',expectedOutput:'1 2 2 3 5 6',isHidden:false}], starterTemplates:TEMPLATES, hints:['Use two pointers'], isPublished:true },
  { title:'Remove Element', slug:'remove-element', difficulty:'Easy' as const, tags:['Array'], description:'## Remove Element\n\nRemove all instances of target value X and print the new array.', constraints:'1<=N<=100', examples:[{input:'4\n3 2 2 3\n3',output:'2 2'}], testCases:[{input:'4\n3 2 2 3\n3',expectedOutput:'2 2',isHidden:false}], starterTemplates:TEMPLATES, hints:['Two pointers'], isPublished:true },
  { title:'Remove Duplicates from Sorted Array', slug:'remove-duplicates-sorted', difficulty:'Easy' as const, tags:['Array'], description:'## Remove Duplicates\n\nRemove duplicates in-place from a sorted array and print unique elements.', constraints:'1<=N<=3*10^4', examples:[{input:'5\n1 1 2 2 3',output:'1 2 3'}], testCases:[{input:'5\n1 1 2 2 3',expectedOutput:'1 2 3',isHidden:false}], starterTemplates:TEMPLATES, hints:['Two pointers'], isPublished:true },
  { title:'Plus One', slug:'plus-one', difficulty:'Easy' as const, tags:['Array','Math'], description:'## Plus One\n\nGiven a non-empty array of digits representing a non-negative integer, increment the integer by one.', constraints:'1<=N<=100', examples:[{input:'3\n1 2 3',output:'1 2 4'}], testCases:[{input:'3\n1 2 3',expectedOutput:'1 2 4',isHidden:false},{input:'1\n9',expectedOutput:'1 0',isHidden:false}], starterTemplates:TEMPLATES, hints:['Handle the carry'], isPublished:true },
  { title:'Rotate Array', slug:'rotate-array', difficulty:'Medium' as const, tags:['Array'], description:'## Rotate Array\n\nRotate an array of N elements to the right by K steps.', constraints:'1<=N<=10^5, 0<=K<=10^5', examples:[{input:'7 3\n1 2 3 4 5 6 7',output:'5 6 7 1 2 3 4'}], testCases:[{input:'7 3\n1 2 3 4 5 6 7',expectedOutput:'5 6 7 1 2 3 4',isHidden:false}], starterTemplates:TEMPLATES, hints:['Reverse parts of the array'], isPublished:true },
  { title:'Missing Number', slug:'missing-number', difficulty:'Easy' as const, tags:['Array','Math'], description:'## Missing Number\n\nGiven array containing N distinct numbers in range [0, N], find the one that is missing.', constraints:'1<=N<=10^4', examples:[{input:'3\n3 0 1',output:'2'}], testCases:[{input:'3\n3 0 1',expectedOutput:'2',isHidden:false},{input:'9\n9 6 4 2 3 5 7 0 1',expectedOutput:'8',isHidden:false}], starterTemplates:TEMPLATES, hints:['Sum of 1..N'], isPublished:true },
  { title:'Single Number', slug:'single-number', difficulty:'Easy' as const, tags:['Array','Bit Manipulation'], description:'## Single Number\n\nEvery element appears twice except for one. Find that single one.', constraints:'1<=N<=3*10^4', examples:[{input:'3\n2 2 1',output:'1'}], testCases:[{input:'3\n2 2 1',expectedOutput:'1',isHidden:false},{input:'5\n4 1 2 1 2',expectedOutput:'4',isHidden:false}], starterTemplates:TEMPLATES, hints:['XOR operator'], isPublished:true },
  { title:'Pascal Triangle', slug:'pascals-triangle', difficulty:'Easy' as const, tags:['Array'], description:'## Pascal Triangle\n\nPrint the first N rows of Pascal triangle.', constraints:'1<=N<=30', examples:[{input:'5',output:'1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1'}], testCases:[{input:'3',expectedOutput:'1\n1 1\n1 2 1',isHidden:false}], starterTemplates:TEMPLATES, hints:['Dynamic Programming'], isPublished:true },
  { title:'Intersection of Two Arrays', slug:'intersection-two-arrays', difficulty:'Easy' as const, tags:['Array','HashSet'], description:'## Array Intersection\n\nFind the intersection of two arrays. Each element in result must be unique.', constraints:'1<=N,M<=1000', examples:[{input:'3 2\n1 2 2\n2 2',output:'2'}], testCases:[{input:'3 2\n1 2 2\n2 2',expectedOutput:'2',isHidden:false}], starterTemplates:TEMPLATES, hints:['Use a set'], isPublished:true },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI as string);
  console.log('Connected to MongoDB');
  let admin = await User.findOne({ email: 'admin@codeforge.dev' });
  if (!admin) {
    admin = await User.create({ username:'admin', email:'admin@codeforge.dev', passwordHash:'Admin@12345', role:'admin' });
    console.log('Admin created');
  }
  for (const p of PROBLEMS) {
    await Problem.findOneAndUpdate(
      { slug: p.slug },
      { ...p, createdBy: admin._id },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`Upserted: ${p.title}`);
  }
  await mongoose.disconnect();
  console.log('Done!');
}
seed().catch(console.error);
