import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Problem from './models/Problem.model';
import User from './models/User.model';
dotenv.config();

const PYTHON_MINIMAL = `def solve():\n    # Write your solution here\n    pass\n\nif __name__ == "__main__":\n    solve()`;
const CPP_MINIMAL = `#include <iostream>\nusing namespace std;\n\nint main() {\n    // Write your solution here\n    return 0;\n}`;
const JAVA_MINIMAL = `import java.util.*;\n\nclass Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // Write your solution here\n    }\n}`;
const JS_MINIMAL = `// Write your solution here\n// Use console.log() to print output`;

const PROBLEMS = [
  { title:'Hello World', slug:'hello-world', difficulty:'Easy' as const, tags:['Basics','I/O'], description:'## Hello World\n\nPrint "Hello, World!" to standard output.', constraints:'No input required\nOutput: Hello, World!', examples:[{input:'',output:'Hello, World!'}], testCases:[{input:'',expectedOutput:'Hello, World!',isHidden:false}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Use print() in Python'], isPublished:true },
  { title:'Sum of Two Numbers', slug:'sum-of-two-numbers', difficulty:'Easy' as const, tags:['Math','I/O'], description:'## Sum of Two Numbers\n\nRead two integers, print their sum.', constraints:'-10^9 <= A,B <= 10^9', examples:[{input:'3\n5',output:'8'}], testCases:[{input:'3\n5',expectedOutput:'8',isHidden:false},{input:'1000000000\n-1000000000',expectedOutput:'0',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Use long long in C++'], isPublished:true },
  { title:'Fibonacci Sequence', slug:'fibonacci-sequence', difficulty:'Easy' as const, tags:['Math','DP'], description:'## Fibonacci\n\nGiven N, print first N Fibonacci numbers.', constraints:'1 <= N <= 40', examples:[{input:'5',output:'0\n1\n1\n2\n3'}], testCases:[{input:'5',expectedOutput:'0\n1\n1\n2\n3',isHidden:false},{input:'10',expectedOutput:'0\n1\n1\n2\n3\n5\n8\n13\n21\n34',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Use two variables'], isPublished:true },
  { title:'Count Word Frequencies', slug:'count-word-frequencies', difficulty:'Medium' as const, tags:['String','HashMap'], description:'## Count Word Frequencies\n\nGiven a sentence, print each word with its count sorted alphabetically.', constraints:'1<=words<=10^4', examples:[{input:'the cat sat on the mat the cat',output:'cat 2\nmat 1\non 1\nsat 1\nthe 3'}], testCases:[{input:'the cat sat on the mat the cat',expectedOutput:'cat 2\nmat 1\non 1\nsat 1\nthe 3',isHidden:false}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Use Counter'], isPublished:true },
  { title:'Reverse a String', slug:'reverse-a-string', difficulty:'Easy' as const, tags:['String','Basics'], description:'## Reverse a String\n\nRead a string and print it reversed.', constraints:'1<=len<=10^5', examples:[{input:'hello',output:'olleh'}], testCases:[{input:'hello',expectedOutput:'olleh',isHidden:false},{input:'abcde',expectedOutput:'edcba',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Slicing works in Python'], isPublished:true },
  { title:'Palindrome Check', slug:'palindrome-check', difficulty:'Easy' as const, tags:['String'], description:'## Palindrome Check\n\nCheck if a string is a palindrome. Print YES or NO.', constraints:'1<=len<=10^5, lowercase only', examples:[{input:'racecar',output:'YES'},{input:'hello',output:'NO'}], testCases:[{input:'racecar',expectedOutput:'YES',isHidden:false},{input:'hello',expectedOutput:'NO',isHidden:false},{input:'abcba',expectedOutput:'YES',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Compare with reversed'], isPublished:true },
  { title:'Find Maximum Element', slug:'find-maximum-element', difficulty:'Easy' as const, tags:['Array'], description:'## Find Maximum\n\nGiven N integers, find the maximum.', constraints:'1<=N<=10^5, -10^9<=arr[i]<=10^9', examples:[{input:'5\n3 1 4 1 5',output:'5'}], testCases:[{input:'5\n3 1 4 1 5',expectedOutput:'5',isHidden:false},{input:'3\n-1 -2 -3',expectedOutput:'-1',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Use built-in max()'], isPublished:true },
  { title:'Binary Search', slug:'binary-search', difficulty:'Easy' as const, tags:['Array','Binary Search'], description:'## Binary Search\n\nGiven a sorted array of N integers and a target T, print the 0-indexed position or -1.', constraints:'1<=N<=10^5', examples:[{input:'5\n1 3 5 7 9\n5',output:'2'}], testCases:[{input:'5\n1 3 5 7 9\n5',expectedOutput:'2',isHidden:false},{input:'4\n2 4 6 8\n5',expectedOutput:'-1',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Halve the search space each step'], isPublished:true },
  { title:'Two Sum', slug:'two-sum', difficulty:'Medium' as const, tags:['Array','HashMap'], description:'## Two Sum\n\nGiven N integers and target T, find two indices (0-indexed) whose values sum to T. Print indices separated by space.', constraints:'2<=N<=10^4, guaranteed one solution', examples:[{input:'4\n2 7 11 15\n9',output:'0 1'}], testCases:[{input:'4\n2 7 11 15\n9',expectedOutput:'0 1',isHidden:false},{input:'3\n3 2 4\n6',expectedOutput:'1 2',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Store complement in a dict'], isPublished:true },
  { title:'Balanced Parentheses', slug:'balanced-parentheses', difficulty:'Medium' as const, tags:['Stack','String'], description:'## Balanced Parentheses\n\nCheck if a string of brackets is balanced. Print YES or NO.', constraints:'1<=len<=10^5, chars from ()[]{}', examples:[{input:'()[]{}'  ,output:'YES'},{input:'([)]',output:'NO'}], testCases:[{input:'()[]{}',expectedOutput:'YES',isHidden:false},{input:'([)]',expectedOutput:'NO',isHidden:false},{input:'{[()]}',expectedOutput:'YES',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Use a stack'], isPublished:true },
  { title:'Bubble Sort', slug:'bubble-sort', difficulty:'Easy' as const, tags:['Array','Sorting'], description:'## Bubble Sort\n\nSort N integers using bubble sort and print the sorted array.', constraints:'1<=N<=10^3', examples:[{input:'5\n5 3 1 4 2',output:'1 2 3 4 5'}], testCases:[{input:'5\n5 3 1 4 2',expectedOutput:'1 2 3 4 5',isHidden:false}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Swap adjacent elements'], isPublished:true },
  { title:'Coin Change (Min Coins)', slug:'coin-change', difficulty:'Medium' as const, tags:['DP','Greedy'], description:'## Coin Change\n\nGiven coin denominations and amount, find minimum coins. Print -1 if impossible.', constraints:'1<=coins<=12, 0<=amount<=10^4', examples:[{input:'3\n1 5 6\n11',output:'2'}], testCases:[{input:'3\n1 5 6\n11',expectedOutput:'2',isHidden:false},{input:'2\n2 5\n3',expectedOutput:'-1',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['DP bottom-up'], isPublished:true },
  { title:'Number of Islands', slug:'number-of-islands', difficulty:'Hard' as const, tags:['Graph','BFS','DFS'], description:'## Number of Islands\n\nGiven an NxM grid of 1s (land) and 0s (water), count distinct islands.', constraints:'1<=N,M<=300', examples:[{input:'4 5\n11110\n11010\n11000\n00000',output:'1'}], testCases:[{input:'4 5\n11110\n11010\n11000\n00000',expectedOutput:'1',isHidden:false},{input:'4 5\n11000\n11000\n00100\n00011',expectedOutput:'3',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['BFS/DFS from each unvisited land cell'], isPublished:true },
  { title:'Trapping Rain Water', slug:'trapping-rain-water', difficulty:'Hard' as const, tags:['Array','Two Pointers'], description:'## Trapping Rain Water\n\nGiven N non-negative heights, compute total water trapped.', constraints:'1<=N<=10^5', examples:[{input:'12\n0 1 0 2 1 0 1 3 2 1 2 1',output:'6'}], testCases:[{input:'12\n0 1 0 2 1 0 1 3 2 1 2 1',expectedOutput:'6',isHidden:false},{input:'6\n4 2 0 3 2 5',expectedOutput:'9',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Two-pointer technique'], isPublished:true },
  { title:'Merge Sort', slug:'merge-sort', difficulty:'Medium' as const, tags:['Array','Sorting','Divide & Conquer'], description:'## Merge Sort\n\nSort N integers using merge sort.', constraints:'1<=N<=10^5', examples:[{input:'6\n38 27 43 3 9 82',output:'3 9 27 38 43 82'}], testCases:[{input:'6\n38 27 43 3 9 82',expectedOutput:'3 9 27 38 43 82',isHidden:false}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Divide then merge'], isPublished:true },
  { title:'Longest Common Subsequence', slug:'longest-common-subsequence', difficulty:'Medium' as const, tags:['DP','String'], description:'## LCS\n\nFind the length of the longest common subsequence of two strings.', constraints:'1<=len<=1000', examples:[{input:'abcde\nace',output:'3'}], testCases:[{input:'abcde\nace',expectedOutput:'3',isHidden:false},{input:'abc\nabc',expectedOutput:'3',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Classic 2D DP'], isPublished:true },
  { title:'N-Queens Problem', slug:'n-queens', difficulty:'Hard' as const, tags:['Backtracking'], description:'## N-Queens\n\nCount distinct ways to place N queens on NxN board with no two attacking each other.', constraints:'1<=N<=12', examples:[{input:'4',output:'2'}], testCases:[{input:'4',expectedOutput:'2',isHidden:false},{input:'8',expectedOutput:'92',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Backtrack with column and diagonal sets'], isPublished:true },
  { title:'Power of a Number', slug:'power-of-number', difficulty:'Easy' as const, tags:['Math','Recursion'], description:'## Fast Power\n\nCompute (base^exp) % (10^9+7).', constraints:'0<=base,exp<=10^9', examples:[{input:'2\n10',output:'1024'}], testCases:[{input:'2\n10',expectedOutput:'1024',isHidden:false},{input:'2\n0',expectedOutput:'1',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Use Python built-in pow with modulus'], isPublished:true },
  { title:'Longest Palindromic Substring', slug:'longest-palindromic-substring', difficulty:'Hard' as const, tags:['DP','String'], description:'## Longest Palindromic Substring\n\nFind the length of the longest palindromic substring.', constraints:'1<=len<=1000', examples:[{input:'babad',output:'3'}], testCases:[{input:'babad',expectedOutput:'3',isHidden:false},{input:'cbbd',expectedOutput:'2',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Expand around center'], isPublished:true },
  { title:'Matrix Spiral Traversal', slug:'matrix-spiral', difficulty:'Medium' as const, tags:['Array','Matrix'], description:'## Spiral Traversal\n\nPrint elements of NxM matrix in spiral order.', constraints:'1<=N,M<=100', examples:[{input:'3 3\n1 2 3\n4 5 6\n7 8 9',output:'1 2 3 6 9 8 7 4 5'}], testCases:[{input:'3 3\n1 2 3\n4 5 6\n7 8 9',expectedOutput:'1 2 3 6 9 8 7 4 5',isHidden:false}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Track four boundaries'], isPublished:true },
  { title:'Stack Using Array', slug:'stack-using-array', difficulty:'Medium' as const, tags:['Stack','Data Structures'], description:'## Stack Simulation\n\nSimulate a stack with PUSH x, POP, and PEEK operations. For POP/PEEK on empty stack print "EMPTY".', constraints:'1<=Q<=10^4', examples:[{input:'5\nPUSH 1\nPUSH 2\nPEEK\nPOP\nPOP',output:'2\n2\n1'}], testCases:[{input:'5\nPUSH 1\nPUSH 2\nPEEK\nPOP\nPOP',expectedOutput:'2\n2\n1',isHidden:false},{input:'2\nPOP\nPEEK',expectedOutput:'EMPTY\nEMPTY',isHidden:true}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Python list works as stack'], isPublished:true },
  { title:'Binary Tree Level Order', slug:'binary-tree-level-order', difficulty:'Medium' as const, tags:['Tree','BFS'], description:'## Level Order Traversal\n\nGiven a binary tree as parent array (1-indexed, -1 for null), print nodes level by level space-separated.', constraints:'1<=N<=10^3', examples:[{input:'7\n-1 1 1 2 2 3 3',output:'1\n2 3\n4 5 6 7'}], testCases:[{input:'7\n-1 1 1 2 2 3 3',expectedOutput:'1\n2 3\n4 5 6 7',isHidden:false}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['BFS with level tracking'], isPublished:true },
  { title:'Dijkstra Shortest Path', slug:'dijkstra-shortest-path', difficulty:'Hard' as const, tags:['Graph','Greedy'], description:'## Dijkstra\n\nFind shortest path from node 1 to all others in weighted graph. Print distances, -1 if unreachable.', constraints:'1<=N,E<=10^4, weights>=0', examples:[{input:'4 4\n1 2 1\n2 3 2\n1 3 4\n3 4 1',output:'0 1 3 4'}], testCases:[{input:'4 4\n1 2 1\n2 3 2\n1 3 4\n3 4 1',expectedOutput:'0 1 3 4',isHidden:false}], starterTemplates:{python:PYTHON_MINIMAL,cpp:CPP_MINIMAL,java:JAVA_MINIMAL,javascript:JS_MINIMAL}, hints:['Min-heap priority queue'], isPublished:true },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI as string);
  console.log('Connected to MongoDB');
  let admin = await User.findOne({ email: 'admin@codeforge.dev' });
  if (!admin) {
    admin = await User.create({ username:'admin', email:'admin@codeforge.dev', passwordHash:'Admin@12345', role:'admin' });
    console.log('Admin created');
  }
  for (const p of PROBLEMS) {
    await Problem.findOneAndUpdate(
      { slug: p.slug },
      { ...p, createdBy: admin._id },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`Upserted: ${p.title}`);
  }
  await mongoose.disconnect();
  console.log('Done!');
}
seed().catch(console.error);
